/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccessStatusDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class AccessStatusDTO {
    @SerializedName("identity")
    private String identity = null;

    @SerializedName("status")
    private String status = null;

    @SerializedName("message")
    private String message = null;

    public AccessStatusDTO identity(String identity) {
        this.identity = identity;
        return this;
    }

    /**
     * The user identity.
     * @return identity
     **/
    @ApiModelProperty(example = "null", value = "The user identity.")
    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

    public AccessStatusDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * The user access status.
     * @return status
     **/
    @ApiModelProperty(example = "null", value = "The user access status.")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public AccessStatusDTO message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Additional details about the user access status.
     * @return message
     **/
    @ApiModelProperty(example = "null", value = "Additional details about the user access status.")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccessStatusDTO accessStatusDTO = (AccessStatusDTO) o;
        return Objects.equals(this.identity, accessStatusDTO.identity) &&
                Objects.equals(this.status, accessStatusDTO.status) &&
                Objects.equals(this.message, accessStatusDTO.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(identity, status, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccessStatusDTO {\n");

        sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

