/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * ConfigVerificationResultDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class ConfigVerificationResultDTO {
    @SerializedName("outcome")
    private OutcomeEnum outcome = null;
    @SerializedName("verificationStepName")
    private String verificationStepName = null;
    @SerializedName("explanation")
    private String explanation = null;

    public ConfigVerificationResultDTO outcome(OutcomeEnum outcome) {
        this.outcome = outcome;
        return this;
    }

    /**
     * The outcome of the verification
     * @return outcome
     **/
    @ApiModelProperty(example = "null", value = "The outcome of the verification")
    public OutcomeEnum getOutcome() {
        return outcome;
    }

    public void setOutcome(OutcomeEnum outcome) {
        this.outcome = outcome;
    }

    public ConfigVerificationResultDTO verificationStepName(String verificationStepName) {
        this.verificationStepName = verificationStepName;
        return this;
    }

    /**
     * The name of the verification step
     * @return verificationStepName
     **/
    @ApiModelProperty(example = "null", value = "The name of the verification step")
    public String getVerificationStepName() {
        return verificationStepName;
    }

    public void setVerificationStepName(String verificationStepName) {
        this.verificationStepName = verificationStepName;
    }

    public ConfigVerificationResultDTO explanation(String explanation) {
        this.explanation = explanation;
        return this;
    }

    /**
     * An explanation of why the step was or was not successful
     * @return explanation
     **/
    @ApiModelProperty(example = "null", value = "An explanation of why the step was or was not successful")
    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConfigVerificationResultDTO configVerificationResultDTO = (ConfigVerificationResultDTO) o;
        return Objects.equals(this.outcome, configVerificationResultDTO.outcome) &&
                Objects.equals(this.verificationStepName, configVerificationResultDTO.verificationStepName) &&
                Objects.equals(this.explanation, configVerificationResultDTO.explanation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(outcome, verificationStepName, explanation);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConfigVerificationResultDTO {\n");

        sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
        sb.append("    verificationStepName: ").append(toIndentedString(verificationStepName)).append("\n");
        sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * The outcome of the verification
     */
    public enum OutcomeEnum {
        @SerializedName("SUCCESSFUL")
        SUCCESSFUL("SUCCESSFUL"),

        @SerializedName("FAILED")
        FAILED("FAILED"),

        @SerializedName("SKIPPED")
        SKIPPED("SKIPPED");

        private String value;

        OutcomeEnum(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }
}

