/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * ParameterContextDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class ParameterContextDTO {
    @SerializedName("name")
    private String name = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("parameters")
    private List<ParameterEntity> parameters = new ArrayList<ParameterEntity>();

    @SerializedName("boundProcessGroups")
    private List<ProcessGroupEntity> boundProcessGroups = new ArrayList<ProcessGroupEntity>();

    @SerializedName("inheritedParameterContexts")
    private List<ParameterContextReferenceEntity> inheritedParameterContexts = new ArrayList<ParameterContextReferenceEntity>();

    @SerializedName("parameterProviderConfiguration")
    private ParameterProviderConfigurationEntity parameterProviderConfiguration = null;

    @SerializedName("id")
    private String id = null;

    public ParameterContextDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The Name of the Parameter Context.
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "The Name of the Parameter Context.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ParameterContextDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * The Description of the Parameter Context.
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "The Description of the Parameter Context.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ParameterContextDTO parameters(List<ParameterEntity> parameters) {
        this.parameters = parameters;
        return this;
    }

    public ParameterContextDTO addParametersItem(ParameterEntity parametersItem) {
        this.parameters.add(parametersItem);
        return this;
    }

    /**
     * The Parameters for the Parameter Context
     * @return parameters
     **/
    @ApiModelProperty(example = "null", value = "The Parameters for the Parameter Context")
    public List<ParameterEntity> getParameters() {
        return parameters;
    }

    public void setParameters(List<ParameterEntity> parameters) {
        this.parameters = parameters;
    }

    public ParameterContextDTO boundProcessGroups(List<ProcessGroupEntity> boundProcessGroups) {
        this.boundProcessGroups = boundProcessGroups;
        return this;
    }

    public ParameterContextDTO addBoundProcessGroupsItem(ProcessGroupEntity boundProcessGroupsItem) {
        this.boundProcessGroups.add(boundProcessGroupsItem);
        return this;
    }

    /**
     * The Process Groups that are bound to this Parameter Context
     * @return boundProcessGroups
     **/
    @ApiModelProperty(example = "null", value = "The Process Groups that are bound to this Parameter Context")
    public List<ProcessGroupEntity> getBoundProcessGroups() {
        return boundProcessGroups;
    }

    public void setBoundProcessGroups(List<ProcessGroupEntity> boundProcessGroups) {
        this.boundProcessGroups = boundProcessGroups;
    }

    public ParameterContextDTO inheritedParameterContexts(List<ParameterContextReferenceEntity> inheritedParameterContexts) {
        this.inheritedParameterContexts = inheritedParameterContexts;
        return this;
    }

    public ParameterContextDTO addInheritedParameterContextsItem(ParameterContextReferenceEntity inheritedParameterContextsItem) {
        this.inheritedParameterContexts.add(inheritedParameterContextsItem);
        return this;
    }

    /**
     * A list of references of Parameter Contexts from which this one inherits parameters
     * @return inheritedParameterContexts
     **/
    @ApiModelProperty(example = "null", value = "A list of references of Parameter Contexts from which this one inherits parameters")
    public List<ParameterContextReferenceEntity> getInheritedParameterContexts() {
        return inheritedParameterContexts;
    }

    public void setInheritedParameterContexts(List<ParameterContextReferenceEntity> inheritedParameterContexts) {
        this.inheritedParameterContexts = inheritedParameterContexts;
    }

    public ParameterContextDTO parameterProviderConfiguration(ParameterProviderConfigurationEntity parameterProviderConfiguration) {
        this.parameterProviderConfiguration = parameterProviderConfiguration;
        return this;
    }

    /**
     * Optional configuration for a Parameter Provider
     * @return parameterProviderConfiguration
     **/
    @ApiModelProperty(example = "null", value = "Optional configuration for a Parameter Provider")
    public ParameterProviderConfigurationEntity getParameterProviderConfiguration() {
        return parameterProviderConfiguration;
    }

    public void setParameterProviderConfiguration(ParameterProviderConfigurationEntity parameterProviderConfiguration) {
        this.parameterProviderConfiguration = parameterProviderConfiguration;
    }

    public ParameterContextDTO id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The ID the Parameter Context.
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "The ID the Parameter Context.")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParameterContextDTO parameterContextDTO = (ParameterContextDTO) o;
        return Objects.equals(this.name, parameterContextDTO.name) &&
                Objects.equals(this.description, parameterContextDTO.description) &&
                Objects.equals(this.parameters, parameterContextDTO.parameters) &&
                Objects.equals(this.boundProcessGroups, parameterContextDTO.boundProcessGroups) &&
                Objects.equals(this.inheritedParameterContexts, parameterContextDTO.inheritedParameterContexts) &&
                Objects.equals(this.parameterProviderConfiguration, parameterContextDTO.parameterProviderConfiguration) &&
                Objects.equals(this.id, parameterContextDTO.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, parameters, boundProcessGroups, inheritedParameterContexts, parameterProviderConfiguration, id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ParameterContextDTO {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("    boundProcessGroups: ").append(toIndentedString(boundProcessGroups)).append("\n");
        sb.append("    inheritedParameterContexts: ").append(toIndentedString(inheritedParameterContexts)).append("\n");
        sb.append("    parameterProviderConfiguration: ").append(toIndentedString(parameterProviderConfiguration)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

