/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AffectedComponentEntity;
import io.swagger.client.model.ParameterContextDTO;
import io.swagger.client.model.RevisionDTO;
import java.util.ArrayList;
import java.util.List;


/**
 * ParameterContextUpdateEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class ParameterContextUpdateEntity   {
  @SerializedName("parameterContextRevision")
  private RevisionDTO parameterContextRevision = null;

  @SerializedName("parameterContext")
  private ParameterContextDTO parameterContext = null;

  @SerializedName("referencingComponents")
  private List<AffectedComponentEntity> referencingComponents = new ArrayList<AffectedComponentEntity>();

  public ParameterContextUpdateEntity parameterContextRevision(RevisionDTO parameterContextRevision) {
    this.parameterContextRevision = parameterContextRevision;
    return this;
  }

   /**
   * The Revision of the Parameter Context
   * @return parameterContextRevision
  **/
  @ApiModelProperty(example = "null", value = "The Revision of the Parameter Context")
  public RevisionDTO getParameterContextRevision() {
    return parameterContextRevision;
  }

  public void setParameterContextRevision(RevisionDTO parameterContextRevision) {
    this.parameterContextRevision = parameterContextRevision;
  }

  public ParameterContextUpdateEntity parameterContext(ParameterContextDTO parameterContext) {
    this.parameterContext = parameterContext;
    return this;
  }

   /**
   * The Parameter Context that is being operated on. This may not be populated until the request has successfully completed.
   * @return parameterContext
  **/
  @ApiModelProperty(example = "null", value = "The Parameter Context that is being operated on. This may not be populated until the request has successfully completed.")
  public ParameterContextDTO getParameterContext() {
    return parameterContext;
  }

  public void setParameterContext(ParameterContextDTO parameterContext) {
    this.parameterContext = parameterContext;
  }

  public ParameterContextUpdateEntity referencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
    return this;
  }

  public ParameterContextUpdateEntity addReferencingComponentsItem(AffectedComponentEntity referencingComponentsItem) {
    this.referencingComponents.add(referencingComponentsItem);
    return this;
  }

   /**
   * The components that are referenced by the update.
   * @return referencingComponents
  **/
  @ApiModelProperty(example = "null", value = "The components that are referenced by the update.")
  public List<AffectedComponentEntity> getReferencingComponents() {
    return referencingComponents;
  }

  public void setReferencingComponents(List<AffectedComponentEntity> referencingComponents) {
    this.referencingComponents = referencingComponents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterContextUpdateEntity parameterContextUpdateEntity = (ParameterContextUpdateEntity) o;
    return Objects.equals(this.parameterContextRevision, parameterContextUpdateEntity.parameterContextRevision) &&
        Objects.equals(this.parameterContext, parameterContextUpdateEntity.parameterContext) &&
        Objects.equals(this.referencingComponents, parameterContextUpdateEntity.referencingComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameterContextRevision, parameterContext, referencingComponents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterContextUpdateEntity {\n");
    
    sb.append("    parameterContextRevision: ").append(toIndentedString(parameterContextRevision)).append("\n");
    sb.append("    parameterContext: ").append(toIndentedString(parameterContext)).append("\n");
    sb.append("    referencingComponents: ").append(toIndentedString(referencingComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

