/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * RelationshipDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class RelationshipDTO {
    @SerializedName("name")
    private String name = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("autoTerminate")
    private Boolean autoTerminate = null;

    @SerializedName("retry")
    private Boolean retry = null;

    public RelationshipDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The relationship name.
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "The relationship name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public RelationshipDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * The relationship description.
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "The relationship description.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public RelationshipDTO autoTerminate(Boolean autoTerminate) {
        this.autoTerminate = autoTerminate;
        return this;
    }

    /**
     * Whether or not flowfiles sent to this relationship should auto terminate.
     * @return autoTerminate
     **/
    @ApiModelProperty(example = "null", value = "Whether or not flowfiles sent to this relationship should auto terminate.")
    public Boolean getAutoTerminate() {
        return autoTerminate;
    }

    public void setAutoTerminate(Boolean autoTerminate) {
        this.autoTerminate = autoTerminate;
    }

    public RelationshipDTO retry(Boolean retry) {
        this.retry = retry;
        return this;
    }

    /**
     * Whether or not flowfiles sent to this relationship should retry.
     * @return retry
     **/
    @ApiModelProperty(example = "null", value = "Whether or not flowfiles sent to this relationship should retry.")
    public Boolean getRetry() {
        return retry;
    }

    public void setRetry(Boolean retry) {
        this.retry = retry;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelationshipDTO relationshipDTO = (RelationshipDTO) o;
        return Objects.equals(this.name, relationshipDTO.name) &&
                Objects.equals(this.description, relationshipDTO.description) &&
                Objects.equals(this.autoTerminate, relationshipDTO.autoTerminate) &&
                Objects.equals(this.retry, relationshipDTO.retry);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, autoTerminate, retry);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RelationshipDTO {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    autoTerminate: ").append(toIndentedString(autoTerminate)).append("\n");
        sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

