/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * StatusHistoryEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class StatusHistoryEntity {
    @SerializedName("statusHistory")
    private StatusHistoryDTO statusHistory = null;

    @SerializedName("canRead")
    private Boolean canRead = null;

    public StatusHistoryEntity statusHistory(StatusHistoryDTO statusHistory) {
        this.statusHistory = statusHistory;
        return this;
    }

    /**
     * Get statusHistory
     * @return statusHistory
     **/
    @ApiModelProperty(example = "null", value = "")
    public StatusHistoryDTO getStatusHistory() {
        return statusHistory;
    }

    public void setStatusHistory(StatusHistoryDTO statusHistory) {
        this.statusHistory = statusHistory;
    }

    public StatusHistoryEntity canRead(Boolean canRead) {
        this.canRead = canRead;
        return this;
    }

    /**
     * Indicates whether the user can read a given resource.
     * @return canRead
     **/
    @ApiModelProperty(example = "null", value = "Indicates whether the user can read a given resource.")
    public Boolean getCanRead() {
        return canRead;
    }

    public void setCanRead(Boolean canRead) {
        this.canRead = canRead;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StatusHistoryEntity statusHistoryEntity = (StatusHistoryEntity) o;
        return Objects.equals(this.statusHistory, statusHistoryEntity.statusHistory) &&
                Objects.equals(this.canRead, statusHistoryEntity.canRead);
    }

    @Override
    public int hashCode() {
        return Objects.hash(statusHistory, canRead);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StatusHistoryEntity {\n");

        sb.append("    statusHistory: ").append(toIndentedString(statusHistory)).append("\n");
        sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

