/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RevisionDTO;
import io.swagger.client.model.VariableRegistryUpdateRequestDTO;


/**
 * VariableRegistryUpdateRequestEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class VariableRegistryUpdateRequestEntity   {
  @SerializedName("request")
  private VariableRegistryUpdateRequestDTO request = null;

  @SerializedName("processGroupRevision")
  private RevisionDTO processGroupRevision = null;

  public VariableRegistryUpdateRequestEntity request(VariableRegistryUpdateRequestDTO request) {
    this.request = request;
    return this;
  }

   /**
   * The Variable Registry Update Request
   * @return request
  **/
  @ApiModelProperty(example = "null", value = "The Variable Registry Update Request")
  public VariableRegistryUpdateRequestDTO getRequest() {
    return request;
  }

  public void setRequest(VariableRegistryUpdateRequestDTO request) {
    this.request = request;
  }

  public VariableRegistryUpdateRequestEntity processGroupRevision(RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
    return this;
  }

   /**
   * The revision for the Process Group that owns this variable registry.
   * @return processGroupRevision
  **/
  @ApiModelProperty(example = "null", value = "The revision for the Process Group that owns this variable registry.")
  public RevisionDTO getProcessGroupRevision() {
    return processGroupRevision;
  }

  public void setProcessGroupRevision(RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryUpdateRequestEntity variableRegistryUpdateRequestEntity = (VariableRegistryUpdateRequestEntity) o;
    return Objects.equals(this.request, variableRegistryUpdateRequestEntity.request) &&
        Objects.equals(this.processGroupRevision, variableRegistryUpdateRequestEntity.processGroupRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, processGroupRevision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryUpdateRequestEntity {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    processGroupRevision: ").append(toIndentedString(processGroupRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

