/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * VersionedParameter
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class VersionedParameter {
    @SerializedName("name")
    private String name = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("sensitive")
    private Boolean sensitive = null;

    @SerializedName("provided")
    private Boolean provided = null;

    @SerializedName("value")
    private String value = null;

    public VersionedParameter name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The name of the parameter
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "The name of the parameter")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public VersionedParameter description(String description) {
        this.description = description;
        return this;
    }

    /**
     * The description of the param
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "The description of the param")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public VersionedParameter sensitive(Boolean sensitive) {
        this.sensitive = sensitive;
        return this;
    }

    /**
     * Whether or not the parameter value is sensitive
     * @return sensitive
     **/
    @ApiModelProperty(example = "null", value = "Whether or not the parameter value is sensitive")
    public Boolean getSensitive() {
        return sensitive;
    }

    public void setSensitive(Boolean sensitive) {
        this.sensitive = sensitive;
    }

    public VersionedParameter provided(Boolean provided) {
        this.provided = provided;
        return this;
    }

    /**
     * Whether or not the parameter value is provided by a ParameterProvider
     * @return provided
     **/
    @ApiModelProperty(example = "null", value = "Whether or not the parameter value is provided by a ParameterProvider")
    public Boolean getProvided() {
        return provided;
    }

    public void setProvided(Boolean provided) {
        this.provided = provided;
    }

    public VersionedParameter value(String value) {
        this.value = value;
        return this;
    }

    /**
     * The value of the parameter
     * @return value
     **/
    @ApiModelProperty(example = "null", value = "The value of the parameter")
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VersionedParameter versionedParameter = (VersionedParameter) o;
        return Objects.equals(this.name, versionedParameter.name) &&
                Objects.equals(this.description, versionedParameter.description) &&
                Objects.equals(this.sensitive, versionedParameter.sensitive) &&
                Objects.equals(this.provided, versionedParameter.provided) &&
                Objects.equals(this.value, versionedParameter.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, sensitive, provided, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VersionedParameter {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    sensitive: ").append(toIndentedString(sensitive)).append("\n");
        sb.append("    provided: ").append(toIndentedString(provided)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

