/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RegisteredFlowSnapshotMetadata;


/**
 * VersionedFlowSnapshotMetadataEntity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-11T13:57:19.352+09:00")
public class VersionedFlowSnapshotMetadataEntity   {
  @SerializedName("versionedFlowSnapshotMetadata")
  private RegisteredFlowSnapshotMetadata versionedFlowSnapshotMetadata = null;

  @SerializedName("registryId")
  private String registryId = null;

  public VersionedFlowSnapshotMetadataEntity versionedFlowSnapshotMetadata(RegisteredFlowSnapshotMetadata versionedFlowSnapshotMetadata) {
    this.versionedFlowSnapshotMetadata = versionedFlowSnapshotMetadata;
    return this;
  }

   /**
   * The collection of registered flow snapshot metadata
   * @return versionedFlowSnapshotMetadata
  **/
  @ApiModelProperty(example = "null", value = "The collection of registered flow snapshot metadata")
  public RegisteredFlowSnapshotMetadata getVersionedFlowSnapshotMetadata() {
    return versionedFlowSnapshotMetadata;
  }

  public void setVersionedFlowSnapshotMetadata(RegisteredFlowSnapshotMetadata versionedFlowSnapshotMetadata) {
    this.versionedFlowSnapshotMetadata = versionedFlowSnapshotMetadata;
  }

  public VersionedFlowSnapshotMetadataEntity registryId(String registryId) {
    this.registryId = registryId;
    return this;
  }

   /**
   * The ID of the Registry that this flow belongs to
   * @return registryId
  **/
  @ApiModelProperty(example = "null", value = "The ID of the Registry that this flow belongs to")
  public String getRegistryId() {
    return registryId;
  }

  public void setRegistryId(String registryId) {
    this.registryId = registryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionedFlowSnapshotMetadataEntity versionedFlowSnapshotMetadataEntity = (VersionedFlowSnapshotMetadataEntity) o;
    return Objects.equals(this.versionedFlowSnapshotMetadata, versionedFlowSnapshotMetadataEntity.versionedFlowSnapshotMetadata) &&
        Objects.equals(this.registryId, versionedFlowSnapshotMetadataEntity.registryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionedFlowSnapshotMetadata, registryId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionedFlowSnapshotMetadataEntity {\n");
    
    sb.append("    versionedFlowSnapshotMetadata: ").append(toIndentedString(versionedFlowSnapshotMetadata)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

