/**
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 * <p>
 * OpenAPI spec version: 1.19.1
 * Contact: dev@nifi.apache.org
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PortEntity;
import io.swagger.client.model.PortRunStatusEntity;
import org.junit.Test;

/**
 * API tests for OutputportsApi
 */
public class OutputportsApiTest {

    private final OutputportsApi api = new OutputportsApi();


    /**
     * Gets an output port
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOutputPortTest() throws ApiException {
        String id = null;
        // PortEntity response = api.getOutputPort(id);

        // TODO: test validations
    }

    /**
     * Deletes an output port
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeOutputPortTest() throws ApiException {
        String id = null;
        String version = null;
        String clientId = null;
        Boolean disconnectedNodeAcknowledged = null;
        // PortEntity response = api.removeOutputPort(id, version, clientId, disconnectedNodeAcknowledged);

        // TODO: test validations
    }

    /**
     * Updates an output port
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOutputPortTest() throws ApiException {
        String id = null;
        PortEntity body = null;
        // PortEntity response = api.updateOutputPort(id, body);

        // TODO: test validations
    }

    /**
     * Updates run status of an output-port
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRunStatusTest() throws ApiException {
        String id = null;
        PortRunStatusEntity body = null;
        // ProcessorEntity response = api.updateRunStatus(id, body);

        // TODO: test validations
    }

}
